food/urls.py
#from django.contrib.auth import views as auth_views  #-----
#from django.contrib.auth.views import PasswordResetView ,PasswordResetDoneView ,PasswordResetConfirmView , PasswordResetCompleteView  #-----
from django.urls import path
from food.views import checkout,handlerequest,handlerequest_buynow, home ,cart , show_food_product , add_to_cart , checkout , clear_cart 
from food.views import buynow  



urlpatterns = [
    path('addtocart/<str:slug>' , add_to_cart),
    path('clearcart/' , clear_cart),           #------
    path('product_details/<str:slug>' , show_food_product),
    path('buynow/product/<str:slug>/' , buynow),   #----

    
    path('' ,home , name='homepage'),
    
    path('cart/' ,cart),
    





  

]

home/urls.py
#from django.contrib.auth import views as auth_views  #-----
#from django.contrib.auth.views import PasswordResetView ,PasswordResetDoneView ,PasswordResetConfirmView , PasswordResetCompleteView  #-----
from django.urls import path
from home.views import team, my_cart , my_orders,term_and_condition ,privacy_policy  , return_policy , about_us , contact_us , career
from home.views import PasswordResetView ,PasswordResetDoneView ,PasswordResetConfirmView ,PasswordResetCompleteView



urlpatterns = [

    
    path('' ,home , name='homepage'),
    path('my_orders/' ,my_orders , name='my_orders'),   #------
    path('my_cart/' ,my_cart),  #------
    path('logout/' ,logout),
    path('signup/' ,signup) ,
    



    path('term_and_condition/' , term_and_condition),
    
    path('privacy_policy/' , privacy_policy),
    path('return_policy/' , return_policy),
    path('contact_us/' , contact_us),
    path('career/' , career),
    path('team/',team),
   





    #-------reset password----------#
    path('password_reset/' ,PasswordResetView.as_view(template_name='home/password_reset_form.html') , name ='password_reset') ,
    path('password_reset/done/' ,PasswordResetDoneView.as_view(template_name='home/password_reset_done.html') , name ='password_reset_done') ,
    path('reset/<uidb64>/<token>/' ,PasswordResetConfirmView.as_view(template_name='home/password_reset_confirm.html') , name ='password_reset_confirm') ,
    path('reset/done/' ,PasswordResetCompleteView.as_view(template_name='home/password_reset_complete.html') , name ='password_reset_complete') ,
    #-------reset password----------#


]

my_college_store/urls.py
from django import urls
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from my_college_store import settings
urlpatterns = [
    path('stationary/',include('stationary.urls')),
    path('admin/', admin.site.urls),
    path('' ,include('home.urls')),
    path('foods/',include('food.urls')),
   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




admin.site.site_header = "CLGKART Admin"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "clgkart administration"

food/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.



#----------------------------







# Create your models here.


class Foodproperty(models.Model):
    title=models.CharField(max_length=60 ,null=False)
    slug=models.CharField(max_length=60 , null=False , unique=True)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True
    

class Category(Foodproperty):
    pass

class FoodStore(models.Model):
    name=models.CharField(max_length=80 , null=False)
    sub_name=models.CharField(max_length=15,null=False)
    slug=models.CharField(max_length=150 , null=True , unique=True , default="" )
    description=RichTextField(blank=True,null=True)
    image=models.ImageField(upload_to='upload/images' , null=False)
    price=models.IntegerField(default=0 , null=True)
    discount=models.IntegerField(default=0)
    category=models.ForeignKey(Category , on_delete=models.CASCADE)
    

    def __str__(self):
        return self.name

    
class FoodImage(models.Model):
    foodstore = models.ForeignKey(FoodStore , on_delete=models.CASCADE)
    foodimg =models.ImageField(upload_to='upload/images',null=False)


    def __str__(self):
        return self.foodstore.name


  
class Order_fd(models.Model):
    orderStatus=(
        ('PENDING',"pending"),
        ('PLACED',"placed"),
        ('CANCELED',"canceled"),
        ('COMPLETED',"completed"),
    )
    method=(
        ('COD',"Cash on Delivery"),
        ('ONLINE',"Pay Online"),
       
    )
    college_name=(
        ('Budge Budge Institute of Technology kokata',"Budge Budge Institute of Technology kokata"),
        ('Jagannath Gupta Institue of Medical Science and Hospital',"Jagannath Gupta Institue of Medical Science and Hospital"),
    )
   
    order_status= models.CharField(max_length=15 , choices=orderStatus)
    payment_method= models.CharField(max_length=20 ,default='Cash on Delivery', choices=method)
    college= models.CharField(max_length=60 , choices=college_name , null=False)
    
    pincode= models.IntegerField( null=False)
    phone = models.CharField(max_length=102 , null=False)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    
    
  
class OrderItem_fd(models.Model):
    order= models.ForeignKey(Order_fd, on_delete=models.CASCADE)
    foodstore= models.ForeignKey(FoodStore, on_delete=models.CASCADE)
   

  
class Payment(models.Model):
    order= models.ForeignKey(Order_fd, on_delete=models.CASCADE)
    date=models.DateTimeField(null=False , auto_now_add=True)

    razorpay_signature= models.CharField(max_length=200 ,null=False)

    def __str__(self):
        return self.payment_id

#------------------------




class Carousel(models.Model):
    name=models.CharField(max_length=60 ,null=False)
    image=models.ImageField(upload_to='upload/images' , null=False)
    
    def __str__(self):
        return self.name


class Cart(models.Model):
    foodStore=models.ForeignKey(FoodStore , on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE )
    quantity=models.IntegerField(default=1)

stationary/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from ckeditor.fields import RichTextField


# Create your models here.

class Stationaryproperty(models.Model):
    title=models.CharField(max_length=60 ,null=False)
    slug=models.CharField(max_length=60 , null=False , unique=True)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True
    

class Category(Stationaryproperty):
    pass

class Publication_or_Brand(Stationaryproperty):
    pass

class WritterName(Stationaryproperty):
    pass

class IdealFor(Stationaryproperty):
    pass



    
                
class StationaryStore(models.Model):
    category=models.ForeignKey(Category , on_delete=models.CASCADE)
    name=models.CharField(max_length=80 , null=False)
    sub
    idealfor=models.ForeignKey(IdealFor , on_delete=models.CASCADE)
    description=RichTextField(blank=True,null=True)
    image=models.ImageField(upload_to='upload/images' , null=False)
    price=models.IntegerField(default=0 , null=True)
    discount=models.IntegerField(default=0)
    

    
    def __str__(self):
        return self.name




class StationaryImage(models.Model):
    stationarystore = models.ForeignKey(StationaryStore , on_delete=models.CASCADE)
    stationaryimg =models.ImageField(upload_to='upload/images',null=False)


    def __str__(self):
        return self.stationarystore.name


class Cart_st(models.Model):
    stationarystore=models.ForeignKey(StationaryStore , on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE )
    quantity=models.IntegerField(default=1)



# Create your order models here.

    
  
class Order_st(models.Model):
    orderStatus=(
        ('PENDING',"pending"),
        ('PLACED',"placed"),
        ('CANCELED',"canceled"),
        ('COMPLETED',"completed"),
    )
    method=(
        ('COD',"Cash on Delivery"),
        ('ONLINE',"Pay Online"),
       
    )
    college_name=(
        ('Budge Budge Institute of Technology kokata',"Budge Budge Institute of Technology kokata"),
        ('Jagannath Gupta Institue of Medical Science and Hospital',"Jagannath Gupta Institue of Medical Science and Hospital"),
    )
   
    order_status= models.CharField(max_length=15 , choices=orderStatus)
    payment_method= models.CharField(max_length=20 ,default='Cash on Delivery', choices=method)
    college= models.CharField(max_length=60 , choices=college_name , null=False)
    
    pincode= models.IntegerField( null=False)
    phone = models.CharField(max_length=102 , null=False)
  
    date=models.DateTimeField(null=False , auto_now_add=True)
    
  
class OrderItem_st(models.Model):
    order= models.ForeignKey(Order_st, on_delete=models.CASCADE)
    stationarystore= models.ForeignKey(StationaryStore, on_delete=models.CASCADE)
    quantity=models.IntegerField( null=False)
    price=models.IntegerField( null=False)
    date=models.DateTimeField(null=False , auto_now_add=True)



class Payment_st(models.Model):
    order= models.ForeignKey(Order_st, on_delete=models.CASCADE)
    date=models.DateTimeField(null=False , auto_now_add=True)
 
    payment_request_id= models.CharField(max_length=200 ,null=False)
    razorpay_signature= models.CharField(max_length=200 ,null=False)




    def __str__(self):
        return self.payment_id



  

    
    

food/views/home.py
from django.contrib.auth.models import User
#from django.core import paginator
from django.db.models import query
from django.http import request
from django.shortcuts import render , HttpResponse , redirect
from home.forms.authforms import CustomerCreationForm , CustomerloginForm
from django.contrib.auth import authenticate, forms ,login as loginUser
from math import floor
from django.contrib.auth.decorators import login_required

from food.models import FoodStore ,Category, Cart , Carousel

from home.forms.checkout_form import CheckForm

from django.core.paginator import Paginator

from urllib.parse import urlencode


#instamojo
from my_college_store.settings import API_KEY , AUTH_TOKEN





def home(request):
    query=request.GET
    foodstore = []
    carousel =[]
    carousels=Carousel.objects.all()
    foodstore=FoodStore.objects
    
   1

    
    if categorys!='' and categorys is not None:
        foodstore=foodstore.filter(category__slug=categorys)
    else:
        foodstore = foodstore.all()



    category=Category.objects.all()

    

    paginator = Paginator(foodstore ,8)
    page_object = paginator.get_page(page)

    query = request.GET.copy()
    query['page'] = ''
    pageurl = urlencode(query)
    

    context={
        'page_object':page_object,                #'foodstore':foodstore
        'category':category,
        'pageurl':pageurl,
  
    }
    return render(request , template_name='food/index.html' , context=context)

home/views/authentication.py
from home import views
from django.contrib.auth.models import User
from django.db.models import query
from django.http import request
from django.shortcuts import render , HttpResponse , redirect
from home.forms.authforms import CustomerCreationForm , CustomerloginForm
from django.contrib.auth import authenticate, forms ,login as loginUser
from math import floor
from django.contrib.auth.decorators import login_required

from food.models import FoodStore ,Category, Cart
from stationary.models import Cart_st                         #------
from home.models import Extendeduser
from home.forms.checkout_form import CheckForm


from django.views.generic.base import View
#instamojo
from my_college_store.settings import API_KEY , AUTH_TOKEN





#------------------------loginview---start------------------------------#

class LoginView(View):
    def get(self ,request):
        form= CustomerloginForm()
        next_page= request.GET.get('next')
        if next_page is not None:
            request.session['next_page'] = next_page
       
        context={
          'form':form,
        }
        return render(request , template_name='home/login.html', context=context)
 
    def post(self , request):
        form = CustomerloginForm(data=request.POST)    
        if(form.is_valid()):
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user = authenticate(username=username , password=password)
            print("========111",user)
            if(user):
                loginUser(request , user)
                print("========111",user)
                #{food ,quantity}
                cart=Cart.objects.filter(user=user)  
                session_cart=[]  
                for c in cart:
                    print(c)
                    obj={
                        'food' : c.foodStore.id,
                        'quantity' : c.quantity
                    }
                    session_cart.append(obj)

                request.session['cart']=session_cart    

                #STATIONARY CART
                cart_st=Cart_st.objects.filter(user=user)    #-------
                session_cart_st=[]
                for c in cart_st:
                    obj_st={
                        'stationary' : c.stationarystore.id,
                        'quantity' : c.quantity
                    }
                    session_cart_st.append(obj_st)

                request.session['cart_st']=session_cart_st



                
                
                next_page = request.session.get('next_page')
                if next_page is None:
                    next_page  = 'homepage'
                return redirect(next_page)

          
        else:
            context={
             'form':form,
            }
            return render(request , template_name='home/login.html', context=context)
#---------------------------------loginview---end------------------------#

"""
def login(request):
    
    if(request.method == 'GET'):
        form= CustomerloginForm()
        next_page= request.GET.get('next')
        if next_page is not None:
            request.session['next_page'] = next_page
       
        context={
          'form':form,
        }
        return render(request , template_name='home/login.html', context=context)
        
    else:
        form = CustomerloginForm(data=request.POST)    
        if(form.is_valid()):
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user = authenticate(username=username , password=password)
            if(user):
                loginUser(request , user)

                #{food quantity}
                cart=Cart.objects.filter(user=user)
                session_cart=[]
                for c in cart:
                    obj={
                        'food' : c.foodStore.id,
                        'quantity' : c.quantity
                    }
                    session_cart.append(obj)

                request.session['cart']=session_cart
                next_page = request.session.get('next_page')
                if next_page is None:
                    next_page  = 'homepage'
                return redirect(next_page)

          
        else:
            context={
             'form':form,
            }
            return render(request , template_name='home/login.html', context=context)
            """

#-------------------------logout---start-------------------#

def logout(request):
    request.session.clear()
    return redirect('homepage')

#------------------------logout---end--------------------#


#--------------------signup---start-----------------------#

def signup(request):
    if(request.method == 'GET'):
        form=CustomerCreationForm
        context={
           "form":form
        }
        return render(request , template_name='home/signup.html' , context=context)    
    else:
        form=CustomerCreationForm(request.POST)
        
        if(form.is_valid()):
            
            user=form.save()
            user.email = user.username
            user.save()
            phone=request.POST['phone_number']
            print("--------------------------------")
            print(phone)
            print("------------------------------")
            college=request.POST['college_name']
            print(college)
            pincode=request.POST['pincode']
            print(pincode)

            newextendeduser=Extendeduser(user=user)
            newextendeduser.phone_num=phone
            newextendeduser.college_name=college
            newextendeduser.pincode=pincode
            newextendeduser.save()
            
            return redirect('login')
        else:
            context={
              "form":form
            }
            return render(request , template_name='home/signup.html' , context=context)    


#--------------------------signup---end-------------------------#

home/views/orders.py
from django.contrib.auth.models import User
from django.db.models import query
from django.http import request
from django.shortcuts import render , HttpResponse , redirect
from home.forms.authforms import CustomerCreationForm , CustomerloginForm
from django.contrib.auth import authenticate, forms ,login as loginUser
from math import floor
from django.contrib.auth.decorators import login_required

from food.models import FoodStore ,Category, Cart,Order_fd,OrderItem_fd,Payment

from home.forms.checkout_form import CheckForm

#instamojo
from my_college_store.settings import API_KEY , AUTH_TOKEN
#from instamojo_wrapper import Instamojo



@login_required(login_url='/login/')
def orders(request):
    user= request.user
    context = {
        "order":order
    }
   
    return render(request , template_name='home/orders.html' , context= context)

home/templates/home/about_us.html
{% extends "./base.html" %}


{% block content %}

<div class="container mt-3 mb-5">
    <div>
        <div>
            <h3 class="text-center text-info">
                <u> About Us</u>
            </h3>
        </div>
        <div class=" p-2 bg-light shadow col-lg-8 mx-auto">
        
            
            
            
            <p class="text-uppercase ">
                <b>What is clgkart.com</b>
            </p>
            <p class="pl-2">
                Clgkart is an e-commerce marketplace for college students. 
                <br>
               we covered three category <br>
                (1) food <br>
                (2) stationery <br>
                 (3) daily needs <br>
                  With more than 300 products
                  and 30 plus brands in our category you will find everything you are looking.
                  <br>
                 Choose from a wide range of options in every category, at the best quality available at the lowest prices.
                  your order will be delivered right to your college,
                  <br>
                 You can pay cash on delivery or online using your debit/credit card, UPI id and many more options are available.

            </p>



            


        </div>
    </div>
</div>

{% endblock %}

home/templates/home/career.html
{% extends "./base.html" %}
{% load static%}
{% block linkforcss %} <link rel="stylesheet" href="{% static 'home/css/career_page.css' %}"> {%endblock%}

{% block content %}

<div class="career_1 border border-dark pt-4">
    
        <col class="row">
        <div class=" col-md-7 col-12 mx-auto mt-5 mb-5">
            <h1 class="text-center display-4 text-info"><strong>We're looking for talented guys</strong> </h1>
           
           <h4 class=" text-center text-info">We keep satisfaction as our first priority</h4>
             <br>
           <p class=" text-center text-white"> <strong >Let us give the best</strong></p>
            <br>
            
           <div class="text-center"><button type="button" onclick="togglepopup()" class=" float-center btn btn-primary">check current openings</button></div>
        </div>
    
</div>


<div class="popup bg-info" id="popup-1">
  <div class="overlay"></div>
  <div class="content">
    <div class=" col-md-6 col-12 close-btn" onclick="togglepopup()">&times;</div>
   
    <p>
      <b>Sorry </b>
      currently there is no openings
      <br>please visit this page next time.
    </p>
  </div>
</div>



<script>
  function togglepopup(){
    document.getElementById("popup-1").classList.toggle("active");
    
  }
</script>

{% endblock %}

home/templates/home/login.html
{% extends "./base.html" %}
{% load static%}
{% load crispy_forms_tags %}
{% block linkforcss %} <link rel="stylesheet" href="{% static 'home/css/loginpage.css' %}"> {%endblock%}
{% block title %}login{%endblock%}

{% block content %}
<div class=" main_login ">
    <div class="  p-2 ">
        <div class=" border formdivlogin col-lg-4 bg-info  mx-auto  rounded p-3 mt-2 shadow p-3 mb-5 bg-white rounded ">
            <form  action="/login/"  method="post">
          
             <h5 class=" text-center ">Login Here</h5>
             <hr>
             {{ form|crispy }}
             {% csrf_token %}
             <div class="form-group align-middle">
                 <input class="btn btn-info " type="submit" value="login">
             </div></form>
             <div>
                <a href="{% url 'password_reset' %}">forget password? </a>
                <a href="/signup/">   ||  create new account</a>
           </div>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/my_orders.html
{% extends "./base.html" %}
{% load food_tags %}
{% load order_tags %}
{% block title %}my_orders{%endblock%}
{% block content %}




<div class=" mt-2 col-lg-3  boredr-b mx-auto   rounded  mb-2 ">


    <div class=" ul-center  text-center">
        <ul class="  nav nav-pills " id="pills-tab" role="tablist">
            <li class=" text-center nav-item" role="presentation">
                <a class=" text-center nav-link active" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab"
                    aria-controls="pills-profile" aria-selected="true">Stationary</a>
            </li>
            <li class="  text-center nav-item" role="presentation">
                <a class=" text-center nav-link " id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab"
                    aria-controls="pills-home" aria-selected="false">Food</a>
            </li>
            
    
        </ul>
    </div>


</div>
<div class="tab-content" id="pills-tabContent">

    <!--------------stationary start--------------------------->
    <div class="tab-pane fade show active" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <div class="container mb-5 ">
            {% for order_for_stationary in order_for_stationary %}
            <div class="row  bg-light mt-3 border border-primary ">
                <div class="mx-auto">
                    <h6 class="">Order <span
                            class="badge badge-{% get_order_status_class order_for_stationary.order_status %}">{{order_for_stationary.order_status}}</span>
                        on
                        {{order_for_stationary.date|date}}</h6>
                </div>
                <div class="col-12 mx-auto">
                    <div class="row mt-1 mb-1 gx-3">

                        <div class="  border  col-12 mx-auto main_cart  mb-3 shadow">
                            {% for oi in order_for_stationary.orderitem_st_set.all %}
                            <div class="bg-light p-3">

                                <div class="row ">
                                    <div
                                        class="col-3 mx-auto bg-light d-flex justify-content-center align-item-center product_img">

                                        <div>
                                            <img class="border img-float img rounded-circle" height="50px"
                                                src="{{oi.stationarystore.image.url}}" alt="">
                                            <div class="text-center">
                                                <b>
                                                    {{oi.stationarystore.name}}
                                                </b>

                                            </div>
                                        </div>


                                    </div>
                                    <div class="  col-9 mx-auto px-4 mt-2">
                                        <div class="row">

                                            <div class="   col-4 mx-auto text-center mt-2">
                                                <p><b>Price</b></p>
                                                <p>₹ {{oi.price}}</p>
                                            </div>
                                            <div class="   col-4 mx-auto text-center mt-2">
                                                <p><b>Qty</b></p>
                                                <p>{{oi.quantity}}</p>
                                            </div>
                                            <div class="  col-4 mx-auto text-center mt-2">
                                                <p><b>total</b></p>
                                                <p>₹ {% multiply oi.quantity oi.price %}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            {%endfor%}
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
    <!--------------stationary end--------------------------->




    <!--------------food start--------------------------->
    <div class="tab-pane fade" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <div class="container mb-5 ">
            {% for order_for_food in order_for_food %}
            <div class="row  bg-light mt-3 border border-primary ">
                <div class="mx-auto">
                    <h6  class="">Order <span
                            class="badge badge-{% get_order_status_class order_for_food.order_status %}">{{order_for_food.order_status}}</span>
                        on
                        {{order_for_food.date|date}}</h6 >
                </div>
                <div class="col-12 mx-auto">
                    <div class="row mt-1 mb-1 gx-3">

                        <div class="  border  col-12 mx-auto main_cart  mb-3 shadow">
                            {% for oi in order_for_food.orderitem_fd_set.all %}
                            <div class="bg-light p-3">

                                <div class="row ">
                                    <div
                                        class="col-3 mx-auto bg-light d-flex justify-content-center align-item-center product_img">

                                        <div>
                                            <img class="border img-float img rounded-circle" height="50px"
                                                src="{{oi.foodstore.image.url}}" alt="">
                                            <div class="text-center">
                                                
                                                <b>{{oi.foodstore.name}}</b>

                                            </div>
                                        </div>


                                    </div>
                                    <div class="  col-9 mx-auto px-4 mt-2">
                                        <div class="row">

                                            <div class="   col-4 mx-auto text-center mt-2">
                                                <p><b>Price</b></p>
                                                <p>₹ {{oi.price}}</p>
                                            </div>
                                            <div class="   col-4 mx-auto text-center mt-2">
                                                <p><b>Qty</b></p>
                                                <p>{{oi.quantity}}</p>
                                            </div>
                                            <div class="  col-4 mx-auto text-center mt-2">
                                                <p><b>total</b></p>
                                                <p>₹ {% multiply oi.quantity oi.price %}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            {%endfor%}
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>           
    </div>

    <!------------------food end----------------------->


</div>



{% endblock %}

home/templates/home/password_reset_complete.html
{% extends "./base.html" %}
{% block content %}

<!--Password Reset Complete-->
<div class=" alert alert-success ">
  
<div class="col-lg-4 border border-info col-md-8 col-12 mx-auto border rounded p-3  alert-success " role="alert">
  <h4 class="alert-heading">Well done!</h4>
  <h2 class="font-weight-bold mt-3 text-dark">Password reset complete</h2>
  <hr>
  <p class="text-dark">Your password has been set. You may go ahead and log in now.</p>
  <div class="text-center"> <a href="/login" class="btn btn-primary">Log in</a></div>
</div>

</div>



{% endblock %}

home/templates/home/password_reset_done.html
{% extends "./base.html" %}

{% block content %}

<!--Password reset sent-->

<div class="alert alert-success ">
	<div class="border border-info  alert-success  col-lg-5 mx-auto border rounded p-3">
		<div>
			<h2 class=" text-center text-alert">Password reset sent</h2>
			<hr>
			<p class="text-dark">We've emailed you instructions for setting your password, if an account exists with the
				email you entered. You
				should receive them shortly</p>
			<hr>
			<p class="text-dark">If you don't receive an email, please make sure you've entered the address you registered
				with, and check your spam folder</p>
		</div>
	</div>
</div>






{% endblock %}

home/templates/home/password_reset_email.html
Someone asked for Password for mail {{ email }}.Follw the link below
{{ protocol }}://{{ domain }}{% url "Password_reset_confirm" uidb64=uid token=token %}
your username in case you have forget:{{ user.get_username }}

home/templates/home/password_reset_form.html
{% extends "./base.html" %}


{% block content %}

{% load crispy_forms_tags %}


<div class=" p-2 ">
    <div class="col-lg-4 bg-info  mx-auto border rounded p-3 mt-2 shadow p-3 mb-5 bg-white rounded ">
        <form action="." method="post">

            <h5 class=" text-center ">Reset Password</h5>
            <hr>
            
            <p class="font-italic">Enter your email address below, and we'll email instructions for setting a new one.
            </p>
            <form method="POST">
                {{ form|crispy }}
                {% csrf_token %}
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">Send email</button>
                </div>
            </form>

    </div>
</div>



{% endblock %}