food/urls.py
#from django.contrib.auth import views as auth_views  #-----
#from django.contrib.auth.views import PasswordResetView ,PasswordResetDoneView ,PasswordResetConfirmView , PasswordResetCompleteView  #-----
from django.urls import path
from food.views import checkout,handlerequest,handlerequest_buynow, home ,cart , show_food_product , add_to_cart , checkout , clear_cart 
from food.views import buynow  



urlpatterns = [
    path('addtocart/<str:slug>' , add_to_cart),
    path('clearcart/' , clear_cart),           #------
    path('product_details/<str:slug>' , show_food_product),
    path('buynow/product/<str:slug>/' , buynow),   #----

    
    path('' ,home , name='homepage'),
    
    path('cart/' ,cart),
    





  

]

my_college_store/urls.py
from django import urls
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from my_college_store import settings
urlpatterns = [
    path('stationary/',include('stationary.urls')),
    path('admin/', admin.site.urls),
    path('' ,include('home.urls')),
    path('foods/',include('food.urls')),
   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




admin.site.site_header = "CLGKART Admin"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "clgkart administration"

food/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.



#----------------------------







# Create your models here.


class Foodproperty(models.Model):
    title=models.CharField(max_length=60 ,null=False)
    slug=models.CharField(max_length=60 , null=False , unique=True)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True
    

class Category(Foodproperty):
    pass

class FoodStore(models.Model):
    name=models.CharField(max_length=80 , null=False)
    sub_name=models.CharField(max_length=15,null=False)
    slug=models.CharField(max_length=150 , null=True , unique=True , default="" )
    description=RichTextField(blank=True,null=True)
    image=models.ImageField(upload_to='upload/images' , null=False)
    price=models.IntegerField(default=0 , null=True)
    discount=models.IntegerField(default=0)
    category=models.ForeignKey(Category , on_delete=models.CASCADE)
    

    def __str__(self):
        return self.name

    
class FoodImage(models.Model):
    foodstore = models.ForeignKey(FoodStore , on_delete=models.CASCADE)
    foodimg =models.ImageField(upload_to='upload/images',null=False)


    def __str__(self):
        return self.foodstore.name


  
class Order_fd(models.Model):
    orderStatus=(
        ('PENDING',"pending"),
        ('PLACED',"placed"),
        ('CANCELED',"canceled"),
        ('COMPLETED',"completed"),
    )
    method=(
        ('COD',"Cash on Delivery"),
        ('ONLINE',"Pay Online"),
       
    )
    college_name=(
        ('Budge Budge Institute of Technology kokata',"Budge Budge Institute of Technology kokata"),
        ('Jagannath Gupta Institue of Medical Science and Hospital',"Jagannath Gupta Institue of Medical Science and Hospital"),
    )
   
    order_status= models.CharField(max_length=15 , choices=orderStatus)
    payment_method= models.CharField(max_length=20 ,default='Cash on Delivery', choices=method)
    college= models.CharField(max_length=60 , choices=college_name , null=False)
    
    pincode= models.IntegerField( null=False)
    phone = models.CharField(max_length=102 , null=False)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    
    
  
class OrderItem_fd(models.Model):
    order= models.ForeignKey(Order_fd, on_delete=models.CASCADE)
    foodstore= models.ForeignKey(FoodStore, on_delete=models.CASCADE)
   

  
class Payment(models.Model):
    order= models.ForeignKey(Order_fd, on_delete=models.CASCADE)
    date=models.DateTimeField(null=False , auto_now_add=True)

    razorpay_signature= models.CharField(max_length=200 ,null=False)

    def __str__(self):
        return self.payment_id

#------------------------




class Carousel(models.Model):
    name=models.CharField(max_length=60 ,null=False)
    image=models.ImageField(upload_to='upload/images' , null=False)
    
    def __str__(self):
        return self.name


class Cart(models.Model):
    foodStore=models.ForeignKey(FoodStore , on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE )
    quantity=models.IntegerField(default=1)

home/forms/checkout_form.py
from email import message
from re import I
from django.contrib.auth import models
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from django.forms import fields
from food.models import Order_fd
from home.models import Contact_us

#>>>>--------------Checkform---start---------------#
"""
class CheckForm(forms.ModelForm):
    class Meta:
        model=Order
        fields = ['college','pincode','phone','payment_method']
        
"""
class CheckForm(forms.ModelForm):
    class Meta:
        model=Order_fd
        fields = ['payment_method']

#--------------CustomerCreationform---end---------------<<<<#
class Contact_us_form(forms.ModelForm):
    class Meta:
        model=Contact_us
        fields=['name','email','phone','subject','message']

food/views/cart.py
from django.contrib.auth.models import User
from django.db.models import query
from django.http import request
from django.shortcuts import render , HttpResponse , redirect
from home.forms.authforms import CustomerCreationForm , CustomerloginForm
from django.contrib.auth import authenticate, forms ,login as loginUser
from math import floor
from django.contrib.auth.decorators import login_required

from food.models import FoodStore ,Category, Cart

from home.forms.checkout_form import CheckForm
from stationary.models import StationaryStore
#instamojo

from my_college_store.settings import API_KEY , AUTH_TOKEN




#----------------------cart---start-------------------#

def cart(request):
    print("---------------------------")
    cart=request.session.get('cart')
    if cart is None:
        cart=[]
    for c in cart:
        food_id = c.get('food')    
        food = FoodStore.objects.get(id=food_id)
        c['food']=food

   

    context={
        'cart':cart,
       
    }    
    return render(request , template_name='home/cart.html', context=context )

#-------------------------------cart---end----------------#


#------------------------------clearcart---start----------#

def clear_cart(request):              
    user=None
    if request.user.is_authenticated:
        user=request.user

    cart =[]
    request.session['cart'] = cart

    
    return_url = request.GET.get('return_url')
    return redirect(return_url)

#---------------------clearcart---end-----------------------#



#--------------------add_to_cart----start------------------#

def add_to_cart(request , slug):

    user=None
    if request.user.is_authenticated:
        user = request.user
    food = FoodStore.objects.get(slug=slug)
    cart=request.session.get('cart')

    
    if cart is None:
        cart=[]
    
    flag = True
    for cart_obj in cart:
        f_id = cart_obj.get('food')
        if f_id==food.id:
            
            flag = False
         

    if flag:        
        cart_obj = {
            'food':food.id,
            'quantity': 1      
        }    
        cart.append(cart_obj)
    if user is not None:        
      
        if len(existing)>0:
            
            obj.quantity= obj.quantity+1
            obj.save()
        else:
            c=Cart()
            c.user= user
            c.foodStore=food
            c.quantity=1
            c.save()    
            
        
        
    request.session['cart']=cart

    return_url = request.GET.get('return_url')
    return redirect(return_url)
#------------------add_to_cart---end-----------------#





    

food/views/checkout.py
from django.contrib.auth.models import User
from django.db.models import query
from django.http import request
from django.shortcuts import render , HttpResponse , redirect
from home.forms.authforms import CustomerCreationForm , CustomerloginForm
from django.contrib.auth import authenticate, forms ,login as loginUser
from math import floor
from django.contrib.auth.decorators import login_required


from food.models import FoodStore ,Category, Cart,OrderItem_fd,Order_fd,Payment
from home.models import  Extendeduser
from home.forms.checkout_form import CheckForm
from my_college_store import settings

from stationary.models import StationaryStore , Order_st ,OrderItem_st ,Payment_st ,Cart_st

#instamojo
from my_college_store.settings import API_KEY , AUTH_TOKEN
#from instamojo_wrapper import Instamojo
#API = Instamojo(api_key=API_KEY, auth_token=AUTH_TOKEN, endpoint='https://test.instamojo.com/api/1.1/');
 

#---------------------------------------------------------


import razorpay





#-------------------------------------------------------------------
def cal_total_payable_amount(cart):
    total=0
    for c in cart :
        discount=c.get('food').discount
        price=c.get('food').price
        
        total = total+total_of_single_product

    return total    


def buynow_total_payable_amount(food):
    total=0
    after_discount=food.price - (food.price*food.discount / 100)
    after_discount=floor(after_discount)
    return after_discount
      


#---------------------------------------------------------------------


#------------------------------checkout---start---------food----------#
@login_required(login_url='/login/')
def checkout(request):
    if request.method == 'GET':
       #get request
        form= CheckForm()
        cart=request.session.get('cart')
        if cart is None:
            cart=[]

      
      
        user=None
        if request.user.is_authenticated:
            user=request.user
        

        exu=Extendeduser.objects.filter(user=user)   #---

        
        

        return render(request ,'food/checkout.html' ,{"form" : form , "cart" : cart,"exu":exu})
    else:
        #post request

        form = CheckForm(request.POST)
     
        user=None
        if request.user.is_authenticated:
            user=request.user

        if form.is_valid():
            #payment
            cart= request.session.get('cart')
            if cart is None:
           
  
            
            exu=Extendeduser.objects.filter(user=user) 

            college = None
            pincode=None
            phone = None
            for ex in exu:
                college=ex.college_name
                pincode=ex.pincode
                phone=ex.phone_num
           
   
            #college = form.cleaned_data.get('college')
            #pincode=form.cleaned_data.get('pincode')
            #phone = form.cleaned_data.get('phone')
            payment_method= form.cleaned_data.get('payment_method')
            total=cal_total_payable_amount(cart)
            

            order =Order_fd()
            order.college=college
          
            order.save()

            #saving order_item
            for c in cart:
                
                order_item.foodstore = food
                order_item.save()

            # creating payment
            #for Online payment
            if payment_method == 'ONLINE':
                
                razorpay_client  = razorpay.Client(auth=(settings.keyid, settings.keySecret))

            
                print(callback_url)

                data={
                    'amount':(order.total)*100,
                    "currency": "INR",
                    'receipt': "shoping on clgkart",
                    'notes': {
                        "name":f'{user.first_name} {user.last_name}',
                        "payment for":"online shoping from clgkart"
                    }
                }
                razorpay_order=razorpay_client .order.create(data=data)
                print(razorpay_order['id'])
                payment = Payment()
                payment.order = order
                payment.payment_request_id =razorpay_order['id']
                payment.save()
                context={
                    'order':order,
                    'orders_id' :razorpay_order['id'],
                    'razorpay_merchant_id': settings.keyid ,
                   
                    'user_name':user.get_full_name ,
                    'phone':phone,
                    'email':user.email
                    
                    
                }

                return render(request ,'food/payment.html' ,context=context)






            #for Case on delivery    
            else:
                order.order_status= 'PLACED'
                order.save()

                payment.save()
                
                cart =[]
                request.session['cart'] = cart

                Cart.objects.filter(user = user).delete()

                return redirect('my_orders')   
          
        else:
            return redirect('/foods/checkout/')    
#------------------------------checkout---end---------food----------#



#------------------------------buynow---start---------food----------#
@login_required(login_url='/login/')  
def buynow(request , slug):
    food = FoodStore.objects.get(slug=slug)
    if request.method == 'GET':
       #get request
        form= CheckForm()

        user=None
        if request.user.is_authenticated:
            user=request.user
        

        exu=Extendeduser.objects.filter(user=user) 
        
       
     
        user=None
        if request.user.is_authenticated:
            user=request.user

        if form.is_valid():
            #payment 


            exu=Extendeduser.objects.filter(user=user) 

            college = None
            pincode=None
            phone = None
            for ex in exu:
                college=ex.college_name
                pincode=ex.pincode
                phone=ex.phone_num


            #college= form.cleaned_data.get('college')
            #pincode=form.cleaned_data.get('pincode')
            #phone = form.cleaned_data.get('phone')
            payment_method= form.cleaned_data.get('payment_method')
            total=buynow_total_payable_amount(food)
          
          
            print("p33333333333333333333")
            o
            
            order_item = OrderItem_fd()
            order_item.order = order  
            order_item.price = floor(food.price -( food.price * (food.discount / 100)))
            order_item.quantity = '1'
            order_item.foodstore = food
            order_item.save()

            # creating payment
            #for Online payment
            if payment_method == "ONLINE":
                razorpay_client  = razorpay.Client(auth=(settings.keyid, settings.keySecret))

                callback_url = 'http://'+ str(get_current_site(request))+"/foods/handlerequest_buynow/"
                print(callback_url)

                data={
                    'amount':(order.total)*100,
                    
                razorpay_order=razorpay_client .order.create(data=data)
                print(razorpay_order['id'])
                payment = Payment()
                payment.order = order
                payment.payment_request_id =razorpay_order['id']
                payment.save()
                context={
                    'order':order,
                    'orders_id' :razorpay_order['id'],
                    'razorpay_merchant_id': settings.keyid ,
                    'callback_url':callback_url,
                    'user_name':user.get_full_name ,
                    'phone':phone,
                    'email':user.email
                    
                    
                }

                return render(request ,'food/payment.html' ,context=context)



            #for Case on delivery    
            else:
                order.order_status= 'PLACED'
                order.save()
                payment = Payment()
                payment.order = order
                payment.payment_request_id = 'none'
                payment.payment_id = 'none'
                payment.payment_status =  'none'
                payment.razorpay_signature='none'
                payment.save()
                
                return redirect('my_orders')   
                
               

        else:
            return redirect('/foods/checkout/')    

#------------------------------buynow---end---------food----------#







    
@csrf_exempt
def handlerequest(request):
    user = None
    if request.user.is_authenticated:
        user=request.user
    razorpay_client  = razorpay.Client(auth=(settings.keyid, settings.keySecret))
    if request.method == "POST":
        try:
            payment_id = request.POST.get('razorpay_payment_id','')
            order_id=request.POST.get('razorpay_order_id','')
            signature=request.POST.get('razorpay_signature','')
            params_dict ={
                'razorpay_order_id':order_id,
                'razorpay_payment_id':payment_id,
                'razorpay_signature':signature
            }
            try:
                order_db=Payment.objects.get(payment_request_id=order_id)
                
            except:
                return HttpResponse("505 NOT Found")    
            order_db.payment_id=payment_id
            order_db.razorpay_signature=signature
            
            order_db.save()
            order= order_db.order
            order.order_status= 'PLACED'
            order.save()
            
            result = razorpay_client.utility.verify_payment_signature(params_dict)
                                  
          ()

                    return redirect('my_orders') 
                except:
                    order_db.payment_status='failed'
                    order_db.save()

food/templates/food/base.html
<!--boostrapv4.6-->
{% load static%}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!---cdnj-->



  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
    integrity="sha512-PgQMlq+nqFLV4ylk1gwUOgm6CtIIXkKwaIHp/PAIWHzig/lKZSEGKEysh0TCVbHJXCLN7WetD8TFecIky75ZfQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  
  
  <title>{% block title %}{%endblock%}</title>
 
</head>

<body>
  <!--------------------navbar---start------------------>

  <nav class=" sticky-top  navbar  navbar-expand-lg navbar-dark bg-dark">
   
    <button class="   navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon  "></span>
    </button>
    <a class="navbar-brand text-info " href="/">
    
        <h4 class=" pl-2 text-center"><b class="textinfo">clg</b><b class="text-warning">kart</b></h4>
      
    </a>
    <div class="   navbar-toggler" type="button" data-toggle="collapse" >
      <a href="/my_cart" class="fas fa-cart-arrow-down text-info"></a>
    </div>
    
   
    

     
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item  active">
          <a class="nav-link" href="#"><b>Stationary</b> <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="#"><b>Food</b> <span class="sr-only">(current)</span></a>
        </li>
        
      </ul>
      <ul class="navbar-nav ml-auto">
       

        <li class="nav-item">
          <a class="nav-link" href="#"> <i class="fas fa-cart-arrow-down text-info"></i><b> Cart</b> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><b>Order </b></a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#"><b>{{user.first_name }}</b></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#"><b>Logout</b></a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="#"><b>Login</b></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><b>Signup</b></a>
        </li>
        {% endif %}
      </ul>
    </div>
    
    
  </nav>
  <!-------------------navbar---end---------------------------->




  {% block content %}{%endblock%}



  <!-----------------Footer---start--------------------->

  <footer class="text-center text-lg-start bg-dark text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom ">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block text-white ">
        <p>Get connected with us on social networks:</p>
      </div>
      <!-- Left -->

      <!-- Right -->
      <div>
        <span style="font-size: 2rem; color: lightblue;">
          <a href="https://www.facebook.com/clgkart" class="mr-4 text-reset">
            <i class="fab fa-facebook"></i>
          </a>
        </span>
        <span style="font-size: 2rem; color: lightblue;">
          <a href="https://twitter.com/juned961" class="mr-4 text-reset">
            <i class="fab fa-twitter-square"></i>
          </a>
        </span>
        <span style="font-size: 2rem; color: lightblue;">
          <a href="https://www.instagram.com/junedaslam96/" class="mr-4 text-reset">
            <i class="fab fa-instagram"></i>
          </a>
        </span>
        <span style="font-size: 2rem; color: lightblue;">
          <a href="https://www.linkedin.com/company/clgkart/" class="mr-4 text-reset">
            <i class="fab fa-linkedin"></i>
          </a>
        </span>


      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="text-white ">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              USEFUL LINK
            </h6>
              <p>
              <a href="/about_us" class="text-reset">About Us</a>
            </p>
            <p>
              <a href="/team" class="text-reset">Our Team</a>
            </p>
            <p>
              <a href="/career" class="text-reset">Carrer</a>
            </p>
            <p>
              <a href="/contact_us" class="text-reset">Conatct US</a>
            </p>
            <p>
              <a href="http://127.0.0.1:8000/admin/" class="text-reset">Admin Login</a>
            </p>
            
            

          </div>
          <!-- Grid column -->

          <!-- Grid column -->

          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              POLICY
            </h6>
            <p>
              <a href="/return_policy" class="text-reset">Return Policy</a>
            </p>
            <p>
              <a href="/term_and_condition" class="text-reset">Term Of Use</a>
            </p>
            <p>
              <a href="/privacy_policy" class="text-reset">Privacy</a>
            </p>

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class=" contacts col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase  fw-bold mb-4">
              Contact
            </h6>
            <p><i class="fa fa-home me-3"></i> Budge Budge Institute Of Technology kolkata </p>
            <p> </p>
            <p>
              <i class="fa fa-envelope me-3"></i>
              <a href="mailto:contact.clgkart@gmail.com">contact.clgkart@gmail.com</a>
              
            </p>
            <p><i class="fa fa-phone me-3"></i>
              +91 9097787894
            </p>

          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright

    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05); ">
      © 2021 Copyright:
      <a class="text-reset fw-bold " href="#"><b class="text-white">clgkart</b></a>
    </div>
    Copyright -->
  </footer>

  <!------------------footer---end------------------------->


  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  
</body>

</html>

food/templates/food/buynow.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% load food_tags %}
{% block content %}

<div class="container mt-2 mb-2">


    <div class="row">

        <div class="col-lg-5 col-12 ml- bg-light mx-auto border rounded shadow">
            <div class="">
                <div class=" h5 alert text-center">Total Payable Amount: ₹
                    {% curren food %}</div>
                <hr>
                <form action="/foods/buynow/product/{{food.slug}}/" method="POST">

                    <fieldset disabled>
                        {% for ex in exu %}
                        <div class="mb-3">
                            <label for="disabledTextInput" class="form-label">College</label>
                            <input type="text" id="disabledTextInput" class="form-control" placeholder="{{ex.college_name}}">
                        </div>
                        <div class="mb-3">
                            <label for="disabledTextInput" class="form-label">Phone Numer</label>
                            <input type="text" id="disabledTextInput" class="form-control" placeholder="{{ex.phone_num}}">
                        </div>
                        <div class="mb-3">
                            <label for="disabledTextInput" class="form-label">pincode</label>
                            <input type="text" id="disabledTextInput" class="form-control" placeholder="{{ex.pincode}}">
                        </div>
                       {% endfor %}
                    </fieldset>

                    {% csrf_token %}
                    {{ form|crispy }}
                    <hr>
                    <div class="form-group">
                        <input class="btn btn-info" type="submit" value="Place Order">
                    </div>
                </form>
            </div>
        </div>



    </div>
</div>

{% endblock %}

food/templates/food/food_product_details.html
{% extends "./base.html"%}

{% load food_tags %}
{% block title %}food_product_details{%endblock%}
{% block content %}

<div class="container  pt-2 bg-light ">
    <div class="row ">
        <div class="col-lg-5 col-md-6 col-sm-6 col-12  ">
         
            <div>
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="{{food.image.url}}" class="img-fluid  shadow-sm mb-2 bg-white rounded " alt="...">
                        </div>
                        {% for img in food.foodimage_set.all %}
                        <div class="carousel-item">
                            <img src="{{ img.foodimg.url}}" class=" img-fluid shadow-sm mb-2 bg-white rounded" alt="...">
                        </div>
                        {% endfor %}
                        
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next " href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon " aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

            
        
        </div>
        <div class="col-lg-7 col-md-6 col-sm-6 col-12">
            <div>
                <h5 class="text-center text-wrap">{{food.name}}</h5>
                <hr class="bg-success">
                <p>{{food.description|safe}}</p>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-12">
                    <br>
                    <div class="text-center">
                       
                        <span class="text-danger"><del>₹{{food.price}}</del></span>
                        &nbsp;
                        <span><b>₹{% curren food %}</b></span>
                        <span class="float-right badge badge-warning p-2">save{{food.discount}}%</span>
                    </div>
                    
                    <br>

                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-12  ">
                    <div class="p-2">
                        <a href="/foods/addtocart/{{food.slug}}?return_url={{request.path}}"
                            class="btn btn-outline-dark btn-block bg-success">Add To Cart</a>
                        <a href="/foods/buynow/product/{{food.slug}}" class="btn btn-outline-dark btn-block bg-info">Buy Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

food/templates/food/payment.html
<!--
<button id="rzp-button1">Pay</button>--->
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    var options = {
        "key": "{{razorpay_merchant_id}}", // Enter the Key ID generated from the Dashboard  

        "name": "{{user_name}}",
        "description": "payment on clgkart",
       
        "order_id": "{{ orders_id }}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1    
        "callback_url":"{{callback_url}}",
        "prefill": {
            "name": "{{user_name}}",
            "email": "{{email}}",
            "contact": "{{phone}}"
        },

        "theme": {
            "color": "#3399cc"
        }
    };
    var rzp1 = new Razorpay(options);
    rzp1.on('payment.failed', function (response) {
        
        /**alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);*/
    });
    window.onload = function (e) {
        rzp1.open();
        e.preventDefault();
    }
</script>