food/urls.py
#from django.contrib.auth import views as auth_views  #-----
#from django.contrib.auth.views import PasswordResetView ,PasswordResetDoneView ,PasswordResetConfirmView , PasswordResetCompleteView  #-----
from django.urls import path
from food.views import checkout,handlerequest,handlerequest_buynow, home ,cart , show_food_product , add_to_cart , checkout , clear_cart 
from food.views import buynow  



urlpatterns = [
    path('addtocart/<str:slug>' , add_to_cart),
    path('clearcart/' , clear_cart),           #------
    path('product_details/<str:slug>' , show_food_product),
    path('buynow/product/<str:slug>/' , buynow),   #----

    
    path('' ,home , name='homepage'),
    
    path('cart/' ,cart),
    





  

]

my_college_store/urls.py
from django import urls
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from my_college_store import settings
urlpatterns = [
    path('stationary/',include('stationary.urls')),
    path('admin/', admin.site.urls),
    path('' ,include('home.urls')),
    path('foods/',include('food.urls')),
   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




admin.site.site_header = "CLGKART Admin"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "clgkart administration"

stationary/urls.py
from django.urls import path
from stationary.views import handlerequest,handlerequest_buynow,sthome ,show_stationary_product ,add_to_cart_st ,cart_st,checkout,validatePayment_st,clear_cart,buynow_st,buynow_validatePayment_st

urlpatterns = [
    path('' , sthome),
    path('product/<str:slug>' , show_stationary_product),
    path('addtocart_st/<str:slug>' , add_to_cart_st),
    path('cart_st/' ,cart_st),
    path('clearcart/' , clear_cart),     
    path('checkout/',checkout),
    path('validate_payment_st/' ,validatePayment_st) ,
    path('buynowvalidate_payment/' ,buynow_validatePayment_st) ,
    path('buynow/product/<str:slug>/' ,buynow_st) ,
    path('handlerequest/',handlerequest),
    path('handlerequest_buynow/',handlerequest_buynow)
]

stationary/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from ckeditor.fields import RichTextField


# Create your models here.

class Stationaryproperty(models.Model):
    title=models.CharField(max_length=60 ,null=False)
    slug=models.CharField(max_length=60 , null=False , unique=True)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True
    

class Category(Stationaryproperty):
    pass

class Publication_or_Brand(Stationaryproperty):
    pass

class WritterName(Stationaryproperty):
    pass

class IdealFor(Stationaryproperty):
    pass



    
                
class StationaryStore(models.Model):
    category=models.ForeignKey(Category , on_delete=models.CASCADE)
    name=models.CharField(max_length=80 , null=False)
    sub
    idealfor=models.ForeignKey(IdealFor , on_delete=models.CASCADE)
    description=RichTextField(blank=True,null=True)
    image=models.ImageField(upload_to='upload/images' , null=False)
    price=models.IntegerField(default=0 , null=True)
    discount=models.IntegerField(default=0)
    

    
    def __str__(self):
        return self.name




class StationaryImage(models.Model):
    stationarystore = models.ForeignKey(StationaryStore , on_delete=models.CASCADE)
    stationaryimg =models.ImageField(upload_to='upload/images',null=False)


    def __str__(self):
        return self.stationarystore.name


class Cart_st(models.Model):
    stationarystore=models.ForeignKey(StationaryStore , on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE )
    quantity=models.IntegerField(default=1)



# Create your order models here.

    
  
class Order_st(models.Model):
    orderStatus=(
        ('PENDING',"pending"),
        ('PLACED',"placed"),
        ('CANCELED',"canceled"),
        ('COMPLETED',"completed"),
    )
    method=(
        ('COD',"Cash on Delivery"),
        ('ONLINE',"Pay Online"),
       
    )
    college_name=(
        ('Budge Budge Institute of Technology kokata',"Budge Budge Institute of Technology kokata"),
        ('Jagannath Gupta Institue of Medical Science and Hospital',"Jagannath Gupta Institue of Medical Science and Hospital"),
    )
   
    order_status= models.CharField(max_length=15 , choices=orderStatus)
    payment_method= models.CharField(max_length=20 ,default='Cash on Delivery', choices=method)
    college= models.CharField(max_length=60 , choices=college_name , null=False)
    
    pincode= models.IntegerField( null=False)
    phone = models.CharField(max_length=102 , null=False)
  
    date=models.DateTimeField(null=False , auto_now_add=True)
    
  
class OrderItem_st(models.Model):
    order= models.ForeignKey(Order_st, on_delete=models.CASCADE)
    stationarystore= models.ForeignKey(StationaryStore, on_delete=models.CASCADE)
    quantity=models.IntegerField( null=False)
    price=models.IntegerField( null=False)
    date=models.DateTimeField(null=False , auto_now_add=True)



class Payment_st(models.Model):
    order= models.ForeignKey(Order_st, on_delete=models.CASCADE)
    date=models.DateTimeField(null=False , auto_now_add=True)
 
    payment_request_id= models.CharField(max_length=200 ,null=False)
    razorpay_signature= models.CharField(max_length=200 ,null=False)




    def __str__(self):
        return self.payment_id



  

    
    

food/views/checkout.py
from django.contrib.auth.models import User
from django.db.models import query
from django.http import request
from django.shortcuts import render , HttpResponse , redirect
from home.forms.authforms import CustomerCreationForm , CustomerloginForm
from django.contrib.auth import authenticate, forms ,login as loginUser
from math import floor
from django.contrib.auth.decorators import login_required


from food.models import FoodStore ,Category, Cart,OrderItem_fd,Order_fd,Payment
from home.models import  Extendeduser
from home.forms.checkout_form import CheckForm
from my_college_store import settings

from stationary.models import StationaryStore , Order_st ,OrderItem_st ,Payment_st ,Cart_st

#instamojo
from my_college_store.settings import API_KEY , AUTH_TOKEN
#from instamojo_wrapper import Instamojo
#API = Instamojo(api_key=API_KEY, auth_token=AUTH_TOKEN, endpoint='https://test.instamojo.com/api/1.1/');
 

#---------------------------------------------------------


import razorpay





#-------------------------------------------------------------------
def cal_total_payable_amount(cart):
    total=0
    for c in cart :
        discount=c.get('food').discount
        price=c.get('food').price
        
        total = total+total_of_single_product

    return total    


def buynow_total_payable_amount(food):
    total=0
    after_discount=food.price - (food.price*food.discount / 100)
    after_discount=floor(after_discount)
    return after_discount
      


#---------------------------------------------------------------------


#------------------------------checkout---start---------food----------#
@login_required(login_url='/login/')
def checkout(request):
    if request.method == 'GET':
       #get request
        form= CheckForm()
        cart=request.session.get('cart')
        if cart is None:
            cart=[]

      
      
        user=None
        if request.user.is_authenticated:
            user=request.user
        

        exu=Extendeduser.objects.filter(user=user)   #---

        
        

        return render(request ,'food/checkout.html' ,{"form" : form , "cart" : cart,"exu":exu})
    else:
        #post request

        form = CheckForm(request.POST)
     
        user=None
        if request.user.is_authenticated:
            user=request.user

        if form.is_valid():
            #payment
            cart= request.session.get('cart')
            if cart is None:
           
  
            
            exu=Extendeduser.objects.filter(user=user) 

            college = None
            pincode=None
            phone = None
            for ex in exu:
                college=ex.college_name
                pincode=ex.pincode
                phone=ex.phone_num
           
   
            #college = form.cleaned_data.get('college')
            #pincode=form.cleaned_data.get('pincode')
            #phone = form.cleaned_data.get('phone')
            payment_method= form.cleaned_data.get('payment_method')
            total=cal_total_payable_amount(cart)
            

            order =Order_fd()
            order.college=college
          
            order.save()

            #saving order_item
            for c in cart:
                
                order_item.foodstore = food
                order_item.save()

            # creating payment
            #for Online payment
            if payment_method == 'ONLINE':
                
                razorpay_client  = razorpay.Client(auth=(settings.keyid, settings.keySecret))

            
                print(callback_url)

                data={
                    'amount':(order.total)*100,
                    "currency": "INR",
                    'receipt': "shoping on clgkart",
                    'notes': {
                        "name":f'{user.first_name} {user.last_name}',
                        "payment for":"online shoping from clgkart"
                    }
                }
                razorpay_order=razorpay_client .order.create(data=data)
                print(razorpay_order['id'])
                payment = Payment()
                payment.order = order
                payment.payment_request_id =razorpay_order['id']
                payment.save()
                context={
                    'order':order,
                    'orders_id' :razorpay_order['id'],
                    'razorpay_merchant_id': settings.keyid ,
                   
                    'user_name':user.get_full_name ,
                    'phone':phone,
                    'email':user.email
                    
                    
                }

                return render(request ,'food/payment.html' ,context=context)






            #for Case on delivery    
            else:
                order.order_status= 'PLACED'
                order.save()

                payment.save()
                
                cart =[]
                request.session['cart'] = cart

                Cart.objects.filter(user = user).delete()

                return redirect('my_orders')   
          
        else:
            return redirect('/foods/checkout/')    
#------------------------------checkout---end---------food----------#



#------------------------------buynow---start---------food----------#
@login_required(login_url='/login/')  
def buynow(request , slug):
    food = FoodStore.objects.get(slug=slug)
    if request.method == 'GET':
       #get request
        form= CheckForm()

        user=None
        if request.user.is_authenticated:
            user=request.user
        

        exu=Extendeduser.objects.filter(user=user) 
        
       
     
        user=None
        if request.user.is_authenticated:
            user=request.user

        if form.is_valid():
            #payment 


            exu=Extendeduser.objects.filter(user=user) 

            college = None
            pincode=None
            phone = None
            for ex in exu:
                college=ex.college_name
                pincode=ex.pincode
                phone=ex.phone_num


            #college= form.cleaned_data.get('college')
            #pincode=form.cleaned_data.get('pincode')
            #phone = form.cleaned_data.get('phone')
            payment_method= form.cleaned_data.get('payment_method')
            total=buynow_total_payable_amount(food)
          
          
            print("p33333333333333333333")
            o
            
            order_item = OrderItem_fd()
            order_item.order = order  
            order_item.price = floor(food.price -( food.price * (food.discount / 100)))
            order_item.quantity = '1'
            order_item.foodstore = food
            order_item.save()

            # creating payment
            #for Online payment
            if payment_method == "ONLINE":
                razorpay_client  = razorpay.Client(auth=(settings.keyid, settings.keySecret))

                callback_url = 'http://'+ str(get_current_site(request))+"/foods/handlerequest_buynow/"
                print(callback_url)

                data={
                    'amount':(order.total)*100,
                    
                razorpay_order=razorpay_client .order.create(data=data)
                print(razorpay_order['id'])
                payment = Payment()
                payment.order = order
                payment.payment_request_id =razorpay_order['id']
                payment.save()
                context={
                    'order':order,
                    'orders_id' :razorpay_order['id'],
                    'razorpay_merchant_id': settings.keyid ,
                    'callback_url':callback_url,
                    'user_name':user.get_full_name ,
                    'phone':phone,
                    'email':user.email
                    
                    
                }

                return render(request ,'food/payment.html' ,context=context)



            #for Case on delivery    
            else:
                order.order_status= 'PLACED'
                order.save()
                payment = Payment()
                payment.order = order
                payment.payment_request_id = 'none'
                payment.payment_id = 'none'
                payment.payment_status =  'none'
                payment.razorpay_signature='none'
                payment.save()
                
                return redirect('my_orders')   
                
               

        else:
            return redirect('/foods/checkout/')    

#------------------------------buynow---end---------food----------#







    
@csrf_exempt
def handlerequest(request):
    user = None
    if request.user.is_authenticated:
        user=request.user
    razorpay_client  = razorpay.Client(auth=(settings.keyid, settings.keySecret))
    if request.method == "POST":
        try:
            payment_id = request.POST.get('razorpay_payment_id','')
            order_id=request.POST.get('razorpay_order_id','')
            signature=request.POST.get('razorpay_signature','')
            params_dict ={
                'razorpay_order_id':order_id,
                'razorpay_payment_id':payment_id,
                'razorpay_signature':signature
            }
            try:
                order_db=Payment.objects.get(payment_request_id=order_id)
                
            except:
                return HttpResponse("505 NOT Found")    
            order_db.payment_id=payment_id
            order_db.razorpay_signature=signature
            
            order_db.save()
            order= order_db.order
            order.order_status= 'PLACED'
            order.save()
            
            result = razorpay_client.utility.verify_payment_signature(params_dict)
                                  
          ()

                    return redirect('my_orders') 
                except:
                    order_db.payment_status='failed'
                    order_db.save()

stationary/views/product_page.py
from django.shortcuts import render

from stationary.models import StationaryStore
# Create your views here.




def show_stationary_product(request , slug):
   
    stationary=StationaryStore.objects.get(slug=slug)
    context={
        'stationary':stationary
    }
    return render(request , template_name="stationary/stationary_prduct_details.html" , context=context)

stationary/views/stationary_home.py
from django.shortcuts import render

from stationary.models import StationaryStore , Category


from django.core.paginator import Paginator

from urllib.parse import urlencode
# Create your views here.

"""
def sthome(request):
    stationarystorte=StationaryStore.objects.all()
    for i in stationarystorte:
     print(i)
    context ={
        "stationarystore": stationarystorte
    } 
    return render(request , template_name='stationary/sthome.html',context = context)


"""



def sthome(request):
    query=request.GET
    stationarystore = []
    stationarystore=StationaryStore.objects
    
    categorys = query.get('category')
    page = query.get('page')
    if(page is  None or page == ''):
        page = 1

    
  



    category=Category.objects.all()

    

    paginator = Paginator(stationarystore ,8)
    page_object = paginator.get_page(page)

    query = request.GET.copy()
    query['page'] = ''
    pageurl = urlencode(query)
    print(urlencode(query) , " query")

    context={
        'page_object':page_object,                #'stationarystore':stationarystore
        'category':category,
        'pageurl':pageurl,
    }
    return render(request , template_name='stationary/sthome.html' , context=context)



def show_stationary_product(request , slug):
   
    stationary=StationaryStore.objects.get(slug=slug)
    context={
        'stationary':stationary
    }
    return render(request , template_name="stationary/stationary_prduct_details.html" , context=context)

stationary/templates/stationary/base.html
<!--boostrapv4.6-->
{% load static%}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!---cdnj-->



  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
    integrity="sha512-PgQMlq+nqFLV4ylk1gwUOgm6CtIIXkKwaIHp/PAIWHzig/lKZSEGKEysh0TCVbHJXCLN7WetD8TFecIky75ZfQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  {% block linkforcss %}{%endblock%}
  <title>{% block title %}{%endblock%}</title>
  <style>
    .display-5 {
      font-size: 25px;
      font-weight: 300;
    }
  </style>
</head>

<body>
  
  <nav class=" sticky-top navbar navbar-expand-lg navbar-dark bg-dark">
   
    <button class="   navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon  "></span>
    </button>
    <a class="navbar-brand text-info " href="/">
    
        <h4 class=" pl-2 text-center"><b class="textinfo">clg</b><b class="text-warning">kart</b></h4>
        
      
    </a>
    <div class="   navbar-toggler" type="button" data-toggle="collapse" >
      <a href="/my_cart" class="fas fa-cart-arrow-down text-info"></a>
    </div>
    
   
    

     
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
          <a class="nav-link" href="/stationary"><b>Stationary</b> <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/foods"><b>Food</b> <span class="sr-only">(current)</span></a>
        </li>
        
      </ul>
      <ul class="navbar-nav ml-auto">
        <!--
        <li class="nav-item">
          <a class="nav-link" href="/cart">My Cart <span
              class="badge badge-info">{{request.session.cart|length}}</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/orders">My Order</a>
        </li>
      -->

        <li class="nav-item">
          <a class="nav-link" href="/my_cart"> <i class="fas fa-cart-arrow-down text-info"></i><b> Cart</b> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/my_orders"><b>Order </b></a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#"><b>{{user.first_name}}</b></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/logout"><b>Logout</b></a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/login"><b>Login</b></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/signup"><b>Signup</b></a>
        </li>
        {% endif %}
      </ul>
    </div>
    
    
  </nav>
<!--navbar end-->



  {% block content %}{%endblock%}



  <!-- Footer -->
  <footer class="text-center text-lg-start bg-dark text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom ">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block text-white ">
        <p>Get connected with us on social networks:</p>
      </div>
      <!-- Left -->

      <!-- Right -->
      <div>
        <span style="font-size: 2rem; color: lightblue;">
          <a href="https://www.facebook.com/clgkart" class="mr-4 text-reset">
            <i class="fab fa-facebook"></i>
          </a>
        </span>
        <span style="font-size: 2rem; color: lightblue;">
          <a href="https://twitter.com/juned961" class="mr-4 text-reset">
            <i class="fab fa-twitter-square"></i>
          </a>
        </span>
        <span style="font-size: 2rem; color: lightblue;">
          <a href="https://www.instagram.com/junedaslam96/" class="mr-4 text-reset">
            <i class="fab fa-instagram"></i>
          </a>
        </span>
        <span style="font-size: 2rem; color: lightblue;">
          <a href="https://www.linkedin.com/company/clgkart/" class="mr-4 text-reset">
            <i class="fab fa-linkedin"></i>
          </a>
        </span>
        

      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="text-white ">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              USEFUL LINK
            </h6>
              <p>
              <a href="/about_us" class="text-reset">About Us</a>
            </p>
            <p>
              <a href="/team" class="text-reset">Our Team</a>
            </p>
            <p>
              <a href="/career" class="text-reset">Carrer</a>
            </p>
            <p>
              <a href="/contact_us" class="text-reset">Conatct US</a>
            </p>
            <p>
              <a href="http://127.0.0.1:8000/admin/" class="text-reset">Admin Login</a>
            </p>
            
            

          </div>
          <!-- Grid column -->

          <!-- Grid column -->

          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              POLICY
            </h6>
            <p>
              <a href="/return_policy" class="text-reset">Return Policy</a>
            </p>
            <p>
              <a href="/term_and_condition" class="text-reset">Term Of Use</a>
            </p>
            <p>
              <a href="/privacy_policy" class="text-reset">Privacy</a>
            </p>

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class=" contacts col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase  fw-bold mb-4">
              Contact
            </h6>
            <p><i class="fa fa-home me-3"></i> Budge Budge Institute Of Technology kolkata </p>
            <p> </p>
            <p>
              <i class="fa fa-envelope me-3"></i>
              <a href="mailto:contact.clgkart@gmail.com">contact.clgkart@gmail.com</a>
              
            </p>
            <p><i class="fa fa-phone me-3"></i>
              +91 9097787894
            </p>

          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright 

    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05); ">
      © 2021 Copyright:
      <a class="text-reset fw-bold " href="#"><b class="text-white">clgkart</b></a>
    </div>
    Copyright -->
  </footer>


  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
</body>

</html>

stationary/templates/stationary/buynow.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% load food_tags %}
{% block content %}



<div class="container mt-2 mb-2">


    <div class="row">

        <div class="col-lg-5 col-12 ml- bg-light mx-auto border rounded shadow">
            <div class="">
                <div class=" h5 alert text-center">Total Payable Amount: ₹
                    {% curren stationary %}</div>
                <hr>
                <form action="/stationary/buynow/product/{{stationary.slug}}/" method="POST">

                    <fieldset disabled>
                        {% for ex in exu %}
                        <div class="mb-3">
                            <label for="disabledTextInput" class="form-label">College</label>
                            <input type="text" id="disabledTextInput" class="form-control" placeholder="{{ex.college_name}}">
                        </div>
                        <div class="mb-3">
                            <label for="disabledTextInput" class="form-label">Phone Numer</label>
                            <input type="text" id="disabledTextInput" class="form-control" placeholder="{{ex.phone_num}}">
                        </div>
                        <div class="mb-3">
                            <label for="disabledTextInput" class="form-label">pincode</label>
                            <input type="text" id="disabledTextInput" class="form-control" placeholder="{{ex.pincode}}">
                        </div>
                       {% endfor %}
                    </fieldset>
                    
                    {% csrf_token %}
                    {{ form|crispy }}
                    <hr>
                    <div class="form-group">
                        <input class="btn btn-info" type="submit" value="Place Order">
                    </div>
                </form>
            </div>
        </div>



    </div>
</div>


{% endblock %}

stationary/templates/stationary/payment_failed.html
{% extends "./base.html" %}
{% load food_tags %}
{% block content %}
<br>
<br>
<div class="jumbotron container p-2 alert-danger text-center">
    <h1>Payment Failed</h1>
    <p class="lead">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio beatae ipsum expedita similique illo adipisci quibusdam nihil, dolorem blanditiis minus porro quae, voluptatibus debitis mollitia, culpa dolorum numquam. Quasi aliquid assumenda repudiandae, consectetur perferendis eum aperiam inventore eaque autem quos nulla recusandae nesciunt at delectus nemo, iusto ab? Aperiam!</p>
    <hr class="my-4">
    <p>Your Payment Failed...</p>
</div>

{% endblock %}

stationary/templates/stationary/stationary_prduct_details.html
{% extends "./base.html"%}

{% load food_tags %}
{% block content %}
<!--class="card-img-top"-->

<div class="container  pt-2 bg-light ">
    <div class="row ">
        <div class="col-lg-4 col-md-5 col-sm-6 col-12  ">
            
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{stationary.image.url}}" class="img-fluid  shadow-sm mb-2 bg-white rounded " alt="...">
                    </div>
                    {% for img in stationary.stationaryimage_set.all %}
                    <div class="carousel-item">
                        <img src="{{ img.stationaryimg.url}}" class=" img-fluid shadow-sm mb-2 bg-white rounded" alt="...">
                    </div>
                    {% endfor %}
                    
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
       
        <div class="col-lg-8 col-md-7 col-sm-6 col-12">
            <div>
                <h5 class="text-center text-wrap">{{stationary.name}}</h5>
                <hr class="bg-success">
                <p>{{stationary.description|safe}}</p>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-12">
                    <br>
                    <div class="text-center">
                        <span class="text-danger"><del>₹{{stationary.price}}</del></span>
                        &nbsp;
                        <span><b>₹{% curren stationary %}</b></span>
                        <span class="float-right badge badge-warning p-2">save{{stationary.discount}}%</span>
                    </div>
                    
                    <br>

                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-12  ">
                    <div class="p-2">
                        <a href="/stationary/addtocart_st/{{stationary.slug}}?return_url={{request.path}}"
                            class="btn btn-outline-dark btn-block bg-success">Add To Cart</a>
                        <a href="/stationary/buynow/product/{{stationary.slug}}" class="btn btn-outline-dark btn-block bg-info">Buy Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}